# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: logserver
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: ["ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/ahappypie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/ahappypie/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates: ["ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/ahappypie/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/ahappypie/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/ahappypie/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ahappypie/{{ .ProjectName }}:{{ .Version }}-arm64v8
